join-firework:
    # delay: Delay in seconds
    # firework-style: Default firework style for join firework
    delay: 2
    fireworks: 'spawn'
styles:
    # color: BLACK, SILVER, GRAY, WHITE, MAROON, RED, PURPLE, FUCHSIA, GREEN,
    #        LIME, OLIVE, YELLOW, NAVY, BLUE, TEAL, AQUA or NONE (no explosion)
    # shape: BALL, BALL_LARGE, BURST, CREEPER, STAR or none (no shape)
    # trail: true/false - Whether the firework leaves a trail (diamond effect)
    # power: Represents the amount of used gunpowder to modify the flight time
    spawn:
        color: GREEN
        shape: CREEPER
        trail: true
        power: 1
    christmas:
        color: RED
        shape: BALL_LARGE
        trail: true
        power: 2
system:
    # Will probably spam your console
    debug: false
    # Don't touch this or ninjas will inhibit your fridge!
    config: '0.3.1'
